version: '3'

services:
  api:
    build: ./flask-api
    command: bash -c "./script/wait-for-postgres.sh api-db ./script/db_migration.sh && python main.py"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./flask-api:/code
    tty: true    
    ports:
      - "5000:5000"
    depends_on:
      - api-db
  app:
    build: ./flask-app
    command: bash -c "./script/wait-for-postgres.sh app-db ./script/db_migration.sh && python main.py"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./flask-app:/code
    tty: true    
    ports:
      - "5001:5000"
    depends_on:
      - app-db
  app-db:
    image: postgres:10
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "54328:5432"
    volumes:
      - app-dbdata:/var/lib/postgresql/data
  api-db:
    image: postgres:10
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"    
    ports:
      - "54329:5432"
    volumes:
      - api-dbdata:/var/lib/postgresql/data
volumes:
  api-dbdata:
  app-dbdata:

