version: '3'

services:
  app:
    build: .
    command: bash -c "./script/wait-for-postgres.sh app-db ./script/db_migration.sh && python main.py"
    ports:
      - "5001:5000"
    environment:
      POSTGRES_PASSWORD: "postgres"      
    volumes:
      - .:/code
    tty: true
    depends_on:
      - app-db
  app-db:
    image: postgres:10
    ports:
      - "54328:5432"
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
